# Compose file overriding the `base` copmose file.
# It disables the `restart` policy, to check that the containers do not restart unexpectedly

services:
  web:
    image: smithmicro/n7m-web:latest
    restart: 'no'

  ui:
    image: smithmicro/n7m-ui:latest
    restart: 'no'

  app:
    image: smithmicro/n7m-app:latest
    restart: 'no'

  feed:
    image: smithmicro/n7m-app:latest

  gis:
    image: smithmicro/n7m-gis:latest
    restart: 'no'
    # Define a healthcheck to wait for the postgres container to be online
    healthcheck:
      test: ["CMD", "pg_isready", "--username=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s
